development:
  address: smtp.1und1.de
  port: 25
  authentication: plain
  user_name: info@qifood.eu
  password: test1234
production:
  address: smtp.1und1.com
  port: 25
  authentication: plain
  user_name: info@qifood.eu
  password: test1234