development:
  address: smtp.1und1.de
  port: 25
  authentication: login   
  user_name: info@qifood.eu
  password: test1234
  domain: qifood.eu
production:
  address: smtp.1und1.de
  port: 25
  authentication: login
  user_name: info@qifood.eu
  password: test1234
  domain: qifood.eu
